(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const canvas = $('editorCanvas'), ctx = canvas.getContext('2d');
  const state = { background:null, elements:[], selected:null, mode:'select', action:null, history:[], future:[], zoom:1 };
  const assets = { emoji:['😊','😍','🔥','✨','🎉','❤️','👏','🌈','⭐','💯'], sticker:['GOOD VIBES','WOW!','LOVE','YES!','COOL','HELLO','YAY!','MOOD'], shape:['rect','circle','triangle','star','heart','arrow'] };
  const presets = {
    clean:{font:'Arial',size:64,color:'#ffffff',bold:true,shadow:true,text:'Clean title'}, editorial:{font:'Georgia',size:60,color:'#fffaf2',bold:true,italic:true,shadow:true,text:'A beautiful moment'},
    impact:{font:'Impact',size:76,color:'#ffffff',bold:false,stroke:'#121212',strokeWidth:5,shadow:false,text:'BIG IMPACT'}, neon:{font:'Trebuchet MS',size:65,color:'#dfb8ff',bold:true,shadow:true,shadowColor:'#7c3aed',text:'Neon glow'},
    label:{font:'Arial',size:48,color:'#ffffff',bold:true,background:'#111827',padding:18,text:'THE LABEL'}, quote:{font:'Georgia',size:51,color:'#ffffff',italic:true,shadow:true,text:'“Keep the good days close.”'}
  };
  let snapshotBeforeAction = null, toastTimer;
  const clone = v => JSON.parse(JSON.stringify(v));
  function toast(message){ $('toast').textContent=message; $('toast').classList.add('show'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>$('toast').classList.remove('show'),1800); }
  function capture(){ return clone({elements:state.elements,selected:state.selected}); }
  function pushHistory(before=snapshotBeforeAction){ if(!before) before=capture(); state.history.push(before); if(state.history.length>40)state.history.shift(); state.future=[]; snapshotBeforeAction=null; updateHistoryButtons(); }
  function restore(s){ state.elements=clone(s.elements); state.selected=s.selected; render(); syncProperties(); }
  function undo(){ if(!state.history.length)return; state.future.push(capture()); restore(state.history.pop()); updateHistoryButtons(); }
  function redo(){ if(!state.future.length)return; state.history.push(capture()); restore(state.future.pop()); updateHistoryButtons(); }
  function updateHistoryButtons(){ $('undoBtn').disabled=!state.history.length; $('redoBtn').disabled=!state.future.length; }
  function selected(){ return state.elements.find(e=>e.id===state.selected); }
  function newId(){ return `${Date.now()}-${Math.random().toString(16).slice(2)}`; }
  function baseElement(type, overrides={}){ return {id:newId(),type,x:canvas.width/2,y:canvas.height/2,rotation:0,scale:1,opacity:1,color:'#ffffff',...overrides}; }
  function addElement(el){ pushHistory(capture()); state.elements.push(el); state.selected=el.id; state.mode='select'; $('doodleBtn').textContent='✎ Start doodling'; render(); syncProperties(); }
  function loadImage(file){ if(!file?.type.startsWith('image/')){toast('Please choose an image file.');return;} const reader=new FileReader(); reader.onload=()=>{const img=new Image();img.onload=()=>{const max=1800,ratio=Math.min(1,max/img.width,max/img.height); canvas.width=Math.round(img.width*ratio);canvas.height=Math.round(img.height*ratio);state.background=img;state.elements=[];state.selected=null;state.history=[];state.future=[];$('emptyState').hidden=true; updateCanvasInfo();render();syncProperties();updateHistoryButtons();toast('Image ready to edit');};img.src=reader.result;};reader.readAsDataURL(file); }
  function updateCanvasInfo(){ $('dimensions').textContent=`${canvas.width} × ${canvas.height} px`; applyZoom(); }
  function applyZoom(){ state.zoom=+$('zoom').value/100; canvas.style.width=`${canvas.width*state.zoom}px`;canvas.style.height=`${canvas.height*state.zoom}px`;$('zoomLabel').textContent=`${Math.round(state.zoom*100)}%`; }
  function drawBackground(){ ctx.clearRect(0,0,canvas.width,canvas.height);if(state.background)ctx.drawImage(state.background,0,0,canvas.width,canvas.height);else{ctx.fillStyle='#ffffff';ctx.fillRect(0,0,canvas.width,canvas.height);const g=ctx.createLinearGradient(0,0,canvas.width,canvas.height);g.addColorStop(0,'#f4f0ff');g.addColorStop(1,'#fff7ed');ctx.fillStyle=g;ctx.globalAlpha=.75;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.globalAlpha=1;} }
  function starPath(radius){ ctx.beginPath();for(let i=0;i<10;i++){const r=i%2?radius*.45:radius,a=-Math.PI/2+i*Math.PI/5;const x=Math.cos(a)*r,y=Math.sin(a)*r;i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.closePath(); }
  function heartPath(s){ctx.beginPath();ctx.moveTo(0,s*.4);ctx.bezierCurveTo(-s*.85,-s*.1,-s*.55,-s*.75,0,-s*.35);ctx.bezierCurveTo(s*.55,-s*.75,s*.85,-s*.1,0,s*.4);ctx.closePath();}
  function drawElement(e){ ctx.save();ctx.translate(e.x,e.y);ctx.rotate(e.rotation);ctx.scale(e.scale,e.scale);ctx.globalAlpha=e.opacity;
    if(e.type==='text'||e.type==='sticker'||e.type==='emoji'){ const isEmoji=e.type==='emoji';ctx.font=`${e.italic?'italic ':''}${e.bold?'bold ':''}${e.size}px ${isEmoji?'Arial':e.font}`;ctx.textAlign=e.align||'center';ctx.textBaseline='middle';const metrics=ctx.measureText(e.text),w=metrics.width,h=e.size*1.18;e.baseW=w+(e.padding||0)*2;e.baseH=h+(e.padding||0)*2;if(e.background){ctx.fillStyle=e.background;roundRect(-e.baseW/2,-e.baseH/2,e.baseW,e.baseH,Math.min(14,e.baseH/4));ctx.fill();}if(e.shadow){ctx.shadowColor=e.shadowColor||'rgba(0,0,0,.6)';ctx.shadowBlur=e.shadowColor?22:10;ctx.shadowOffsetY=e.shadowColor?0:5;}if(e.stroke){ctx.strokeStyle=e.stroke;ctx.lineWidth=e.strokeWidth||3;ctx.lineJoin='round';ctx.strokeText(e.text,0,0);}ctx.fillStyle=e.color;ctx.fillText(e.text,0,0); }
    else if(e.type==='shape'){ctx.fillStyle=e.color;const s=e.size;e.baseW=e.kind==='arrow'?s*1.5:s;e.baseH=s;if(e.kind==='rect'){roundRect(-s/2,-s/2,s,s,12);ctx.fill();}else if(e.kind==='circle'){ctx.beginPath();ctx.arc(0,0,s/2,0,Math.PI*2);ctx.fill();}else if(e.kind==='triangle'){ctx.beginPath();ctx.moveTo(0,-s/2);ctx.lineTo(s/2,s/2);ctx.lineTo(-s/2,s/2);ctx.closePath();ctx.fill();}else if(e.kind==='star'){starPath(s/2);ctx.fill();}else if(e.kind==='heart'){heartPath(s*.6);ctx.fill();}else{ctx.beginPath();ctx.moveTo(-s*.75,-s*.16);ctx.lineTo(s*.28,-s*.16);ctx.lineTo(s*.28,-s*.42);ctx.lineTo(s*.75,0);ctx.lineTo(s*.28,s*.42);ctx.lineTo(s*.28,s*.16);ctx.lineTo(-s*.75,s*.16);ctx.closePath();ctx.fill();}}
    else if(e.type==='doodle'){ctx.strokeStyle=e.color;ctx.lineWidth=e.lineWidth;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();e.points.forEach((p,i)=>i?ctx.lineTo(p.x-e.cx,p.y-e.cy):ctx.moveTo(p.x-e.cx,p.y-e.cy));ctx.stroke();}
    ctx.restore(); }
  function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);}
  function bounds(e){return {w:(e.baseW||100)*e.scale,h:(e.baseH||100)*e.scale};}
  function localPoint(e,p){const dx=p.x-e.x,dy=p.y-e.y,c=Math.cos(-e.rotation),s=Math.sin(-e.rotation);return {x:(dx*c-dy*s)/e.scale,y:(dx*s+dy*c)/e.scale};}
  function hitElement(p){for(let i=state.elements.length-1;i>=0;i--){const e=state.elements[i],q=localPoint(e,p);if(Math.abs(q.x)<=(e.baseW||100)/2+12/e.scale&&Math.abs(q.y)<=(e.baseH||100)/2+12/e.scale)return e;}return null;}
  function handles(e){const b=bounds(e),c=Math.cos(e.rotation),s=Math.sin(e.rotation),convert=(x,y)=>({x:e.x+x*c-y*s,y:e.y+x*s+y*c});return {scale:convert(b.w/2,b.h/2),rotate:convert(0,-b.h/2-38)};}
  function drawSelection(){const e=selected();if(!e)return;const b=bounds(e);ctx.save();ctx.translate(e.x,e.y);ctx.rotate(e.rotation);ctx.strokeStyle='#705cf5';ctx.lineWidth=2;ctx.setLineDash([6,4]);ctx.strokeRect(-b.w/2,-b.h/2,b.w,b.h);ctx.setLineDash([]);ctx.beginPath();ctx.moveTo(0,-b.h/2);ctx.lineTo(0,-b.h/2-38);ctx.stroke();ctx.fillStyle='#fff';ctx.strokeStyle='#705cf5';for(const [x,y,r] of [[b.w/2,b.h/2,7],[0,-b.h/2-38,8]]){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.stroke();}ctx.restore();}
  function render(){drawBackground();state.elements.forEach(drawElement);drawSelection();}
  function point(ev){const r=canvas.getBoundingClientRect();return{x:(ev.clientX-r.left)*canvas.width/r.width,y:(ev.clientY-r.top)*canvas.height/r.height};}
  canvas.addEventListener('pointerdown',ev=>{ev.preventDefault();const p=point(ev);canvas.setPointerCapture(ev.pointerId);if(state.mode==='doodle'){snapshotBeforeAction=capture();const e=baseElement('doodle',{points:[p],cx:p.x,cy:p.y,x:p.x,y:p.y,color:$('brushColor').value,lineWidth:+$('brushSize').value,baseW:10,baseH:10});state.elements.push(e);state.selected=e.id;state.action={kind:'draw',e};render();return;}const e=selected(),hs=e&&handles(e);snapshotBeforeAction=capture();if(e&&Math.hypot(p.x-hs.rotate.x,p.y-hs.rotate.y)<16){state.action={kind:'rotate',e,startAngle:Math.atan2(p.y-e.y,p.x-e.x),start:e.rotation};}else if(e&&Math.hypot(p.x-hs.scale.x,p.y-hs.scale.y)<16){state.action={kind:'scale',e,startDist:Math.hypot(p.x-e.x,p.y-e.y),start:e.scale};}else{const hit=hitElement(p);state.selected=hit?.id||null;state.action=hit?{kind:'move',e:hit,dx:p.x-hit.x,dy:p.y-hit.y}:null;syncProperties();render();}});
  canvas.addEventListener('pointermove',ev=>{if(!state.action)return;const p=point(ev),a=state.action;if(a.kind==='move'){a.e.x=p.x-a.dx;a.e.y=p.y-a.dy;}else if(a.kind==='scale'){a.e.scale=Math.max(.1,Math.min(4,a.start*Math.hypot(p.x-a.e.x,p.y-a.e.y)/a.startDist));}else if(a.kind==='rotate'){a.e.rotation=a.start+Math.atan2(p.y-a.e.y,p.x-a.e.x)-a.startAngle;}else if(a.kind==='draw'){a.e.points.push(p);const xs=a.e.points.map(v=>v.x),ys=a.e.points.map(v=>v.y);a.e.cx=(Math.min(...xs)+Math.max(...xs))/2;a.e.cy=(Math.min(...ys)+Math.max(...ys))/2;a.e.x=a.e.cx;a.e.y=a.e.cy;a.e.baseW=Math.max(10,Math.max(...xs)-Math.min(...xs)+a.e.lineWidth);a.e.baseH=Math.max(10,Math.max(...ys)-Math.min(...ys)+a.e.lineWidth);}render();syncSliders();});
  function pointerUp(){if(state.action){pushHistory(snapshotBeforeAction);state.action=null;if(state.mode==='doodle'){state.mode='select';$('doodleBtn').textContent='✎ Start doodling';syncProperties();}}} canvas.addEventListener('pointerup',pointerUp);canvas.addEventListener('pointercancel',pointerUp);
  function syncSliders(){const e=selected();if(!e)return;$('rotation').value=Math.round(e.rotation*180/Math.PI);$('rotationValue').textContent=`${$('rotation').value}°`;$('scale').value=Math.round(e.scale*100);$('scaleValue').textContent=`${$('scale').value}%`;}
  function setSheet(open){$('propertiesSheet').classList.toggle('open',open);$('sheetHandle').setAttribute('aria-expanded',String(open));}
  function syncProperties(){const e=selected();$('propertiesEmpty').hidden=!!e;$('propertyPanel').hidden=!e;if(!e){setSheet(false);return;}if(matchMedia('(max-width: 680px)').matches)setSheet(true);const textLike=['text','sticker','emoji'].includes(e.type);$('textProperties').hidden=!textLike;if(textLike){$('editText').value=e.text;$('fontFamily').value=e.font||'Arial';$('fontSize').value=e.size;$('textAlign').value=e.align||'center';$('boldBtn').classList.toggle('active',!!e.bold);$('italicBtn').classList.toggle('active',!!e.italic);$('shadowBtn').classList.toggle('active',!!e.shadow);}$('elementColor').value=e.color;$('opacity').value=e.opacity*100;syncSliders();}
  function mutate(fn){const before=capture();fn(selected());pushHistory(before);render();syncProperties();}
  $('addTextBtn').onclick=()=>addElement(baseElement('text',{text:$('newText').value.trim()||'Your text',font:'Arial',size:64,bold:true,align:'center',shadow:true}));
  document.querySelectorAll('.preset').forEach(btn=>btn.onclick=()=>{const p=presets[btn.dataset.style];addElement(baseElement('text',{...p,align:'center',opacity:1}));});
  function renderAssets(type='emoji'){$('assetGrid').innerHTML='';assets[type].forEach(item=>{const b=document.createElement('button');b.className=`asset ${type==='shape'?'shape':''}`;b.textContent=type==='shape'?({rect:'■',circle:'●',triangle:'▲',star:'★',heart:'♥',arrow:'➜'}[item]):item;b.title=`Add ${item}`;b.onclick=()=>{if(type==='shape')addElement(baseElement('shape',{kind:item,size:130,baseW:item==='arrow'?195:130,baseH:130,color:'#6657e8'}));else if(type==='emoji')addElement(baseElement('emoji',{text:item,size:100,font:'Arial',color:'#ffffff',baseW:100,baseH:115}));else addElement(baseElement('sticker',{text:item,size:38,font:'Arial',bold:true,color:'#ffffff',background:'#6657e8',padding:15,baseW:190,baseH:75}));};$('assetGrid').appendChild(b);});}
  document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===t));renderAssets(t.dataset.tab);});renderAssets();
  $('doodleBtn').onclick=()=>{state.mode=state.mode==='doodle'?'select':'doodle';$('doodleBtn').textContent=state.mode==='doodle'?'✓ Doodle mode on':'✎ Start doodling';canvas.style.cursor=state.mode==='doodle'?'crosshair':'default';};
  $('sheetHandle').onclick=()=>setSheet(!$('propertiesSheet').classList.contains('open'));
  const liveProps={editText:(e,v)=>e.text=v,fontFamily:(e,v)=>e.font=v,fontSize:(e,v)=>e.size=+v,textAlign:(e,v)=>e.align=v,elementColor:(e,v)=>e.color=v,opacity:(e,v)=>e.opacity=+v/100,rotation:(e,v)=>e.rotation=+v*Math.PI/180,scale:(e,v)=>e.scale=+v/100};
  Object.entries(liveProps).forEach(([id,set])=>{const el=$(id);el.addEventListener('pointerdown',()=>snapshotBeforeAction=capture());el.addEventListener('input',()=>{const e=selected();if(e){set(e,el.value);render();syncSliders();}});el.addEventListener('change',()=>{if(snapshotBeforeAction)pushHistory(snapshotBeforeAction);});});
  [['boldBtn','bold'],['italicBtn','italic'],['shadowBtn','shadow']].forEach(([id,key])=>$(id).onclick=()=>mutate(e=>e[key]=!e[key]));
  function remove(){if(!selected())return;mutate(e=>{state.elements=state.elements.filter(x=>x!==e);state.selected=null;});}
  $('deleteBtn').onclick=remove;$('duplicateBtn').onclick=()=>{const e=selected();if(!e)return;const copy=clone(e);copy.id=newId();copy.x+=25;copy.y+=25;addElement(copy);};
  $('forwardBtn').onclick=()=>mutate(e=>{const i=state.elements.indexOf(e);if(i<state.elements.length-1)[state.elements[i],state.elements[i+1]]=[state.elements[i+1],state.elements[i]];});
  $('backBtn').onclick=()=>mutate(e=>{const i=state.elements.indexOf(e);if(i>0)[state.elements[i],state.elements[i-1]]=[state.elements[i-1],state.elements[i]];});
  $('fileInput').onchange=e=>loadImage(e.target.files[0]);const dz=$('dropZone');['dragenter','dragover'].forEach(n=>dz.addEventListener(n,e=>{e.preventDefault();dz.classList.add('drag');}));['dragleave','drop'].forEach(n=>dz.addEventListener(n,e=>{e.preventDefault();dz.classList.remove('drag');}));dz.addEventListener('drop',e=>loadImage(e.dataTransfer.files[0]));
  $('zoom').oninput=applyZoom;$('undoBtn').onclick=undo;$('redoBtn').onclick=redo;$('newBtn').onclick=()=>{if(!confirm('Start a new design? Your current edits will be cleared.'))return;state.background=null;state.elements=[];state.selected=null;state.history=[];state.future=[];canvas.width=1000;canvas.height=700;$('emptyState').hidden=false;updateCanvasInfo();render();syncProperties();updateHistoryButtons();};
  $('downloadBtn').onclick=()=>{const old=state.selected;state.selected=null;render();const a=document.createElement('a');a.download=`pixelpop-${new Date().toISOString().slice(0,10)}.png`;a.href=canvas.toDataURL('image/png');a.click();state.selected=old;render();toast('PNG downloaded');};
  document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();}else if(e.key==='Delete'||e.key==='Backspace')remove();else if(e.key==='Escape'){state.selected=null;state.mode='select';render();syncProperties();}});
  updateCanvasInfo();render();
})();
